/**
 * Service Worker registration and management for PWA
 * Note: The actual service worker is generated by vite-plugin-pwa
 */

export async function registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
  if (!('serviceWorker' in navigator)) {
    console.log('Service Workers not supported');
    return null;
  }

  try {
    // vite-plugin-pwa handles the SW registration automatically
    // This function checks if a SW is registered and returns it
    const registration = await navigator.serviceWorker.ready;
    console.log('Service Worker ready:', registration.scope);
    return registration;
  } catch (error) {
    console.error('Service Worker not available:', error);
    return null;
  }
}

export async function checkForServiceWorkerUpdate(): Promise<boolean> {
  if (!('serviceWorker' in navigator)) {
    return false;
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    await registration.update();
    return !!registration.waiting;
  } catch (error) {
    console.error('Error checking for SW update:', error);
    return false;
  }
}

export async function skipWaitingAndReload(): Promise<void> {
  if (!('serviceWorker' in navigator)) {
    return;
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    if (registration.waiting) {
      registration.waiting.postMessage({ type: 'SKIP_WAITING' });
      window.location.reload();
    }
  } catch (error) {
    console.error('Error skipping waiting:', error);
  }
}

export function onServiceWorkerUpdate(callback: () => void): () => void {
  if (!('serviceWorker' in navigator)) {
    return () => {};
  }

  const handleControllerChange = () => {
    callback();
  };

  navigator.serviceWorker.addEventListener('controllerchange', handleControllerChange);
  
  return () => {
    navigator.serviceWorker.removeEventListener('controllerchange', handleControllerChange);
  };
}

export async function isServiceWorkerActive(): Promise<boolean> {
  if (!('serviceWorker' in navigator)) {
    return false;
  }

  try {
    const registration = await navigator.serviceWorker.getRegistration();
    return !!registration?.active;
  } catch {
    return false;
  }
}
